Planet_Names:
  - Sun
  - Venus
  - Mercury
  - Earth
  - Mars
  - Jupiter
  - Saturn
  - Uranus
  - Neptune

Planet_Colors:
  Sun: (255, 255, 0)
  Venus: (165, 50, 50)
  Mercury: (150, 255, 20)
  Earth: (0, 0, 255)

Planet_Masses:
  Sun: 3.8e+17
  Venus: 4.39e+4
  Mercury: 3.94e+5
  Earth: 5.9e+6
  Mars: 5.6e+4
  Jupiter: 6
  Saturn: 7
  Uranus: 8
  Neptune: 9

Planet_Radii:
  Sun: 30
  Venus: 10
  Mercury: 8
  Earth: 12
  Mars: 5
  Jupiter: 6
  Saturn: 7
  Uranus: 8
  Neptune: 9

Planet_Positions:
  Sun: (0.0, 0.0)
  Venus: (-50.0, 300.0)
  Mercury: (100.0, -200.0)
  Earth: (0, -500)

Planet_Velocities:
  Sun: (0.0, 0.0)
  Venus: (1.0, 0.025)
  Mercury: (-1.5, 0.05)
  Earth: (1.2, .025)

Constants:
  Astronomical_Unit: 149.6e6 * 1000
  Gravitational_Constant: 6.67428e-11
  Universal_Scale: 250

Window:
  Height: 1040
  Width: 1660
  Background: (0, 0, 0)
  Title: "Solar System Simulation"
